### ISSUE TITLE
Scale Colorbar correctly for categorical data

### ISSUE THREAD

**Issue by TonioF** [xcube-dev/xcube-viewer#306]
The xcube viewer provides access to colorbars that may serve to show categorical data. When these color bars are used, every color should correspond to one value in the dataset. However, the color ranges are scaled to the value range of the data, which can cause that it is not obvious to see which color belongs to which category.

It would be ideal to support a clear mapping of colors to categories along with a customisable categorical colorbar that fits the data at hand.

**Comment by forman** [comment]
I fully agree. Will take care of that asap.

**Comment by forman** [comment]
@TonioF, see PR #328, which is the groundwork for resolving this issue.

**Comment by forman** [comment]
Should be closed by #391
