### ISSUE TITLE
time series bar chart not working in firefox

### ISSUE THREAD

**Issue by KerstinS** [xcube-dev/xcube-viewer#380]
the bar chart option for the time series is not shown for me when using firefoy. It works propoerly in chrome. 
low priority - we can tell users to use another browser.

**Comment by forman** [comment]
Have you tried reloading the app and/or make sure to get rid of [outdated cached browser data](https://support.mozilla.org/en-US/kb/how-clear-firefox-cache).

**Comment by KerstinS** [comment]
I did this now and it works fine! Thank you.
